structures:
  - id: "3LZG"
    protein: "HA"
    subtype: "H1N1"
    description: "2009 H1N1 influenza hemagglutinin, A/California/04/2009"
  - id: "3VUN"
    protein: "HA"
    subtype: "H3N2"
    description: "H3 influenza hemagglutinin, A/Aichi/2/1968"
  - id: "3NSS"
    protein: "NA"
    subtype: "H1N1"
    description: "2009 H1N1 influenza neuraminidase N1"
  - id: "6BR6"
    protein: "NA"
    subtype: "H3N2"
    description: "H3N2 influenza neuraminidase N2"
